# Generated by Django 5.1.6 on 2023-07-26 14:15

from django.db import migrations, models
from django.core.validators import RegexValidator


def add_default_emails(apps, schema_editor):
    """
    Add default unique emails to existing faculty members
    """
    Faculty = apps.get_model('schedules', 'Faculty')
    for i, faculty in enumerate(Faculty.objects.all()):
        faculty.email = f"professor{i}@up.edu.ph"
        faculty.save()


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_adminuser_department_faculty_classsection_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.EmailField(
                max_length=254,
                default='faculty@up.edu.ph',
                validators=[
                    RegexValidator(
                        regex=r'^[\w\.-]+@up\.edu\.ph$',
                        message='Email must be in the format: "example@up.edu.ph"',
                        code='invalid_email'
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.RunPython(add_default_emails),
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(
                max_length=254,
                validators=[
                    RegexValidator(
                        regex=r'^[\w\.-]+@up\.edu\.ph$',
                        message='Email must be in the format: "example@up.edu.ph"',
                        code='invalid_email'
                    )
                ],
                unique=True
            ),
        ),
    ] 