# Generated by Django 5.1.6 on 2025-05-19 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_faculty_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_users', to='schedules.department'),
        ),
    ]
