# Generated by Django 5.1.6 on 2025-05-19 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_adminuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_users', to='schedules.department'),
        ),
    ]
