name: Docker Build and Test

on:
    # push:
    #     branches-ignore: ["main"]
    # pull_request:
    workflow_dispatch: # Trigger manually for now

env:
    AWS_REGION: ap-southeast-1
    ECR_REPOSITORY: upcampus

permissions:
    contents: read

jobs:
    build-and-test:
        name: Build and Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Delete .env file
              run: |
                  rm -f .env
                  touch .env

            - name: Create .env file
              env:
                  SECRET_KEY: ${{ secrets.SECRET_KEY }}
                  DB_NAME: ${{ secrets.DB_NAME }}
                  DB_USER: ${{ secrets.DB_USER }}
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                  DB_HOST: ${{ secrets.DB_HOST }}
                  DB_PORT: ${{ secrets.DB_PORT }}
                  DEBUG: "False"
              run: |
                  echo "SECRET_KEY=${SECRET_KEY}" > .env
                  echo "DB_NAME=${DB_NAME}" >> .env
                  echo "DB_USER=${DB_USER}" >> .env
                  echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
                  echo "DB_HOST=${DB_HOST}" >> .env
                  echo "DB_PORT=${DB_PORT}" >> .env
                  echo "DEBUG=False" >> .env

            - name: Build Docker image
              run: |
                  docker build -t upcampus:test .

            - name: Run tests
              run: |
                  docker run upcampus:test python src/manage.py test
