name: Docker Build and Test SQLite

on:
    push:
        branches-ignore: ["main"]
    pull_request:

permissions:
    contents: read

jobs:
    build-and-test:
        name: Build and Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Delete .env file
              run: |
                  rm -f .env
                  touch .env

            - name: Create .env file
              env:
                  SECRET_KEY: ${{ secrets.SECRET_KEY }}
                  DEBUG: "False"
              run: |
                  echo "SECRET_KEY=${SECRET_KEY}" > .env
                  echo "DEBUG=False" >> .env

            - name: Build Docker image
              run: |
                  docker build -t upcampus:test .

            - name: Run Migrations
              run: |
                  docker run upcampus:test python src/manage.py migrate

            - name: Run tests
              run: |
                  docker run upcampus:test python src/manage.py test
